collections:
  authors:
    output: true
  houses:
    output: true
  apartments:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "houses"
    values:
      layout: "house"
  - scope:
      path: ""
      type: "apartments"
    values:
      layout: "apartment"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"